# Generated by Django 5.1.2 on 2024-10-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_watch_alter_match_date_alter_match_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='date',
            new_name='match_time',
        ),
    ]
