version: 0.0
os: linux
files:
  - source: /
    destination: /Cricketschedule_project/cricketschedule_project
hooks:
  AfterInstall:
    - location: deploy/restart_server.sh
      timeout: 300
      runas: ubuntu
