version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/CricketScheduleDevopsProject
permissions:
  - object: /home/ubuntu/CricketScheduleDevopsProject
    owner: ubuntu
    group: www-data
    mode: 755
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: deploy/scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy/scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: deploy/scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  BeforeAllowTraffic:
    - location: deploy/scripts/set_permissions.sh
      timeout: 300
      runas: ubuntu
