version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/yourapp

hooks:
  AfterInstall:
    - location: deploy/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: deploy/start_server.sh
      timeout: 60
      runas: ec2-user
