version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Pre-build: Preparing Django environment...
      - python manage.py collectstatic --noinput
      - python manage.py migrate
  build:
    commands:
      - echo Build: Testing the application...
      - python manage.py test
artifacts:
  files:
    - '**/*'
  discard-paths: no
