version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Running tests...
      - python manage.py test
  build:
    commands:
      - echo Build phase complete
artifacts:
  files:
    - '**/*'
    - appspec.yml
    - deploy/scripts/*
